### ISSUE TITLE
[DOUBT] Problems implementing a "wrapper" promise

### ISSUE THREAD

**Issue by castarco** [guzzle/promises#24]
Hello,

I'm implementing a DB client for a database using `HTTP` as its wire protocol. I'm trying to implement a wrapper for the promises returned by the `Guzzle\Client`, but it's clear that I've misunderstood something about this library ^_^ .

Before starting delving into details, my problem seems to be simple: In theory my code is pretending to "catch" Guzzle's exceptions and wrapping it with my own class. What is happening is the Guzzle exception is thrown at some point which I can't identify, and remains uncaught.

Here you can see my code, full of debug prints:

```php
<?php


namespace Druid4PHP\Responses;


use Druid4PHP\Errors\DruidRequestError;
use Druid4PHP\Errors\DruidServerError;
use Druid4PHP\Errors\DruidResponseParseError;
use Druid4PHP\Queries\Query;

use GuzzleHttp\Promise\Promise;
use GuzzleHttp\Promise\PromiseInterface;

use Psr\Http\Message\ResponseInterface;


/**
 * @method Response|array wait($unwrap = true)
 */
final class AsyncResponse extends Promise
{
    /** @var Query */
    private $query;

    /** @var PromiseInterface */
    private $httpPromise;
    
    /** @var bool */
    private $encapsulation;

    /**
     * AsyncResponse constructor.
     * @param Query $query
     * @param PromiseInterface $httpPromise
     * @param bool $encapsulation
     */
    public function __construct(Query $query, PromiseInterface $httpPromise, $encapsulation = true)
    {
        echo "\nINSIDE __construct\n";
        
        $this->query = $query;
        $this->httpPromise = $httpPromise->then(
            function (ResponseInterface $response) {
                echo "\nIN A FEW nanos WE'LL GET INTO this->onFulfilledHttpPromise\n";
                return $this->onFulfilledHttpPromise($response);
            },
            function (\Exception $e) {
                echo "\nIN A FEW nanos WE'LL GET INTO this->onRejectedHttpPromise\n";
                return $this->onRejectedHttpPromise($e);
            }
        );
        $this->encapsulation = $encapsulation;
        
        parent::__construct(
            function () {
                echo "\nIN A FEW nanos WE'LL GET INTO this->waitHandler\n";
                return $this->waitHandler();
            },
            function () {
                echo "\nIN A FEW nanos WE'LL GET INTO this->cancelHandler\n";
                return $this->cancelHandler();
            }
        );

        echo "\nGOING OUT OF __construct\n";
    }
    
    private function waitHandler()
    {
        echo "\nNOW WE'LL CALL httpPromise->wait\n";

        $this->httpPromise->wait();

        echo "\nNOW WE'VE CALLED httpPromise->wait\n\n";
    }
    
    private function cancelHandler()
    {
        echo "\nNOW WE'LL CALL httpPromise->cancel\n";
        
        $this->httpPromise->cancel();

        echo "\nNOW WE'VE CALLED httpPromise->cancel\n";
    }

    private function onFulfilledHttpPromise(ResponseInterface $response)
    {
        echo "\nINSIDE onFulfilledHttpPromise\n";
        
        // TODO: allow stream decoding without having to call getContents.
        $rawResponse = $response->getBody()->getContents();
        $rawResults = json_decode($rawResponse, true);

        if (JSON_ERROR_NONE !== json_last_error()) {
            throw new DruidResponseParseError($this->query, $rawResponse, 'Received invalid JSON');
        }

        echo "\nIN A FEW nanos WE'll GO INSIDE this->resolve\n";
        
        $this->resolve(
            $this->encapsulation ? $this->query->parseResponse($rawResults) : $rawResults
        );

        echo "\nGOING OUT OF onFulfilledHttpPromise\n";
    }

    private function onRejectedHttpPromise(\Exception $e)
    {
        echo "\nINSIDE onRejectedHttpPromise (".get_class($this).")\n";
        
        $eCode = $e->getCode();
        if ($eCode >= 500 && $eCode < 600) {
            $this->reject(new DruidServerError($this->query, $e));
        } else {
            $this->reject(new DruidRequestError($this->query, $e));
        }

        echo "\nGOING OUT OF onRejectedHttpPromise\n";
    }
}
```

and here you can see the output of one of my executions:

```

Starting with timeseries queries:

INSIDE __construct

GOING OUT OF __construct

IN A FEW nanos WE'LL GET INTO this->waitHandler

NOW WE'LL CALL httpPromise->wait

IN A FEW nanos WE'LL GET INTO this->onRejectedHttpPromise

INSIDE onRejectedHttpPromise (Druid4PHP\Responses\AsyncResponse)

GOING OUT OF onRejectedHttpPromise

NOW WE'VE CALLED httpPromise->wait

PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST http://127.0.0.1:8082/druid/v2/` resulted in a `500 Internal Server Error` response:
{"error":"Instantiation of [simple type, class io.druid.query.timeseries.TimeseriesQuery] value failed: Missing fields [ (truncated...)
' in /home/acorrea/PhpstormProjects/Druid4PHP/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /home/acorrea/PhpstormProjects/Druid4PHP/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/acorrea/PhpstormProjects/Druid4PHP/vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/acorrea/PhpstormProjects/Druid4PHP/vendor/guzzlehttp/promises/src/Promise.php(154): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/acorrea/PhpstormProjects/ in /home/acorrea/PhpstormProjects/Druid4PHP/src/Responses/AsyncResponse.php on line 116
```

what is surprising to me is the exception is being thrown after this piece if code ( `$this->httpPromise->wait();` ) gets executed, and not during its execution.

Any idea to fix my implementation?

Thank you in advance.

**Comment by castarco** [comment]
I'll close this issue. I wasn't capturing my own exception to see the crash on the console as I said.

The weird fact is that PHP showed me the Guzzle exception instead of my wrapper exception in the console output, but the thrown exception was the one I constructed, not the Guzzle's one.

I think this is a PHP "bug" rather than a flaw in my code or in Guzzle's code.
